"use client";
import { useMemo, useState } from "react";
import type { Product } from "@/lib/types";
import { ProductCard } from "./product-card";

const choices = (items: Product[], key: keyof Product) => [...new Set(items.map(x => x[key]).filter(Boolean) as string[])].sort();
export function CatalogueClient({ initialProducts }: { initialProducts: Product[] }) {
  const [query, setQuery] = useState(""); const [results, setResults] = useState<Product[] | null>(null); const [loading, setLoading] = useState(false);
  const [brand, setBrand] = useState(""); const [category, setCategory] = useState(""); const [condition, setCondition] = useState(""); const [maxPrice, setMaxPrice] = useState(""); const [sort, setSort] = useState("newest");
  const products = useMemo(() => { let x = results ?? initialProducts; if (brand) x=x.filter(p=>p.brand===brand); if(category)x=x.filter(p=>p.category===category); if(condition)x=x.filter(p=>p.condition===condition); if(maxPrice)x=x.filter(p=>p.price_cents<=Number(maxPrice)*100); return [...x].sort((a,b)=>sort==="price-asc"?a.price_cents-b.price_cents:sort==="price-desc"?b.price_cents-a.price_cents:0); },[results,initialProducts,brand,category,condition,maxPrice,sort]);
  async function search(e: React.FormEvent){e.preventDefault();if(!query.trim()){setResults(null);return}setLoading(true);try{const response=await fetch("/api/search",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({query})});const data=await response.json();setResults(data.products??[]);}finally{setLoading(false)}}
  function changeQuery(value:string){setQuery(value);if(!value.trim())setResults(null);}
  return <><section className="hero"><div className="shell"><div className="eyebrow">The considered collection</div><h1>Handbags with a story worth carrying forward.</h1><p>Exceptional pre-owned pieces, selected for their enduring design, condition and character.</p><form className="search" onSubmit={search}><input aria-label="Search naturally" value={query} onChange={e=>changeQuery(e.target.value)} placeholder="Try “a classic evening bag under S$3,000”"/><button className="button">{loading?"Searching…":"Find your bag"}</button></form></div></section><section id="shop" className="section shell"><div className="section-head"><div><div className="eyebrow">Browse the archive</div><h2>Available now</h2></div><select className="sort" value={sort} onChange={e=>setSort(e.target.value)}><option value="newest">Newest</option><option value="price-asc">Price: low to high</option><option value="price-desc">Price: high to low</option></select></div><div className="catalogue"><aside className="filters"><label>Brand</label><select value={brand} onChange={e=>setBrand(e.target.value)}><option value="">All brands</option>{choices(initialProducts,"brand").map(x=><option key={x}>{x}</option>)}</select><label>Category</label><select value={category} onChange={e=>setCategory(e.target.value)}><option value="">All categories</option>{choices(initialProducts,"category").map(x=><option key={x}>{x}</option>)}</select><label>Condition</label><select value={condition} onChange={e=>setCondition(e.target.value)}><option value="">All conditions</option>{choices(initialProducts,"condition").map(x=><option value={x} key={x}>{x}</option>)}</select><label>Maximum price (SGD)</label><select value={maxPrice} onChange={e=>setMaxPrice(e.target.value)}><option value="">Any price</option><option value="1500">Under S$1,500</option><option value="3000">Under S$3,000</option><option value="5000">Under S$5,000</option></select></aside><div>{results&&<p className="meta">Semantic matches for “{query}”</p>}<div className="grid">{products.map(p=><ProductCard key={p.id} product={p}/>)}</div>{!products.length&&<div className="empty">No bags match this edit. Try broadening your search or filters.</div>}</div></div></section></>;
}
