import { NextResponse } from "next/server";
import OpenAI from "openai";
import { z } from "zod";
import { assistantSearch } from "@/lib/retrieval";
import { money } from "@/lib/types";
const schema=z.object({message:z.string().trim().min(2).max(700),productIds:z.array(z.string().uuid()).max(12).optional()});
const client=()=>new OpenAI({apiKey:process.env.CLASSGW_KEY,baseURL:process.env.COGNITIOLABS_CHAT_BASE_URL??"https://174.138.16.223/v1"});
export async function POST(request:Request){try{const {message}=schema.parse(await request.json());const retrieval=await assistantSearch(message,8);const {products}=retrieval;const context=products.map(p=>({id:p.id,slug:p.slug,brand:p.brand,model:p.model,title:p.title,category:p.category,price:money(p.price_cents),condition:p.condition,description:p.description,colour:p.colour,material:p.material,size:p.size,hardware:p.hardware,condition_notes:p.condition_notes,included_items:p.included_items,style_tags:p.style_tags,occasion_tags:p.occasion_tags,image_urls:p.image_urls,authenticity_status:p.authenticity_status,authenticity_notes:p.authenticity_notes,seller_name:p.seller_name,seller_location:p.seller_location,is_available:p.is_available,created_at:p.created_at}));const completion=await client().chat.completions.create({model:process.env.COGNITIOLABS_CHAT_MODEL??"gpt-5.6-terra",temperature:0,tools:[{type:"function",function:{name:"return_catalogue_answer",description:"Return the grounded buyer-assistant response with the catalogue listings it relies on.",parameters:{type:"object",properties:{answer:{type:"string"},productIds:{type:"array",items:{type:"string"}}},required:["answer","productIds"],additionalProperties:false}}}],tool_choice:{type:"function",function:{name:"return_catalogue_answer"}},messages:[{role:"system",content:"You are Atelier Archive's Buyer Assistant. Use only the supplied catalogue records to describe products or make product claims. Do not claim or imply shipping, delivery, returns, availability beyond the supplied record, authentication evidence beyond its supplied fields, dimensions, provenance, or any other fact that is not present. If the shopper asks for an absent fact, say: 'The catalogue does not provide that information.' Use supplied price strings exactly; do not expose cents or convert currency. For a broad recommendation, select relevant supplied records and include every recommended record ID in productIds. Recommend only supplied IDs. If comparison lookup reports unmatched named comparison requests, clearly say that no catalogue record was provided for each one; do not infer any product details from its name."},{role:"user",content:`Question: ${message}\n\nComparison lookup (routing metadata, not product facts):\n${JSON.stringify({requestedTerms:retrieval.comparisonTerms,unmatchedNamedRequests:retrieval.unmatchedComparisonTerms})}\n\nCatalogue context:\n${JSON.stringify(context)}`} ]});const call=completion.choices[0]?.message.tool_calls?.[0] as {function?:{arguments:string}}|undefined;const parsed=z.object({answer:z.string(),productIds:z.array(z.string()).default([])}).parse(JSON.parse(call?.function?.arguments??"{}"));const valid=new Set(products.map(p=>p.id));const cited=products.filter(p=>parsed.productIds.includes(p.id)&&valid.has(p.id));
// A model omission must not turn a grounded recommendation into unlinked prose.
// The fallback is still exclusively the listings retrieved for this question.
const displayed=new Map<string,typeof products[number]>();
for(const product of [...retrieval.namedProducts,...cited]) displayed.set(product.id,product);
return NextResponse.json({answer:parsed.answer,products:displayed.size?[...displayed.values()]:products.slice(0,3)});}catch(error){console.error("Assistant failed",error);return NextResponse.json({error:"The Buyer Assistant is unavailable right now. Please try again shortly."},{status:500});}}
